### ISSUE TITLE
double nodes in UaExpert

### ISSUE THREAD

**Issue by ReStone** [ChimeraTK/ControlSystemAdapter-OPC-UA-Adapter#10]
UaExpert sees all Root/Objects/Server - nodes twice in the DemoServer (Tag v1.0) adress space:
![double nodes](https://cloud.githubusercontent.com/assets/19655759/17973625/79b5c12e-6ae3-11e6-80eb-45b05cc7b9e9.PNG)

Is that wanted behaviour?

**Comment by jmrahm** [comment]
Issue #3 from report.
Working in progress ;-)

**Comment by ichrispa** [comment]
The cause was found and fixed in open62541. The duplicated should be gone now.

**Comment by ichrispa** [comment]
Still occuring in subdirectories (Telco), reopened.

**Comment by zenker** [comment]
Fixed long time ago.
