### ISSUE TITLE
News on data type error with LabVIEW Client

### ISSUE THREAD

**Issue by ReStone** [ChimeraTK/ControlSystemAdapter-OPC-UA-Adapter#13]
The item data type read by LabVIEW has been allways "0" in tag v1.0:
![item data type tag1 0](https://cloud.githubusercontent.com/assets/19655759/18717909/e2e054a4-8021-11e6-97af-18fb0a492b66.PNG)

With tag v1.1 it changed to the value "24":
![item data type tag1 1](https://cloud.githubusercontent.com/assets/19655759/18717951/0f295cc2-8022-11e6-8ceb-f5d7192d3171.PNG)

Maybe that tells you something!?

**Comment by ReStone** [comment]
NI answered a support request concerning the data type issue:

> I have tried the Windows 32 bit Demo Server on the following link. And I can read correct data type in the Server nodes. 
> 
> http://open62541.org/
> 
> And  then I double checked the two pictures in the original post. I found the "ValueRank" in two pictures are different.
> 
> Developer helped check source code for me that we do not support "ValueRank=0" . I think that might be the reason of this issue.
>  
> And I checked the Demo Server code; I found it only defines ValueRank = 1 data type. That is why the 
 Demo Server is working well.
>  
> BTW, "ValueRank = 1" means the data is one dimension array; and "ValueRank= -1" means the data is a scalar. And currently we don't support "ValueRank = 0". 

Additional remarks:
LabVIEW seems to read the data type directly from „DataType.Identifier“. This only works when „ValueRank“ != 0
- For Tag 1.0, „ValueRank“ was 0, hence „DataType.Identifier“ was not be read correctly
- For Tag 1.1 „ValueRank“ is -1 but „DataType.Identifier“ allways reads 24, what is correctly read by LabVIEW but does not represent a valid type

**Comment by jmrahm** [comment]
Hi, in the current master branch the ValueRank is consequently set to -3, the meaning is "ScalarOrOneDimension" (see IEC62541 Part 3), hence we support both types. Typical scalar values and array with one dimension. I would be glad if you can check the support in LabViwe.

The other Point... currently the stack change a little bit. So the DataType is set to a kind of generic Datatype "BaseDataType" with identifier "24". Therefore the LabView output is "correct". But the more specific Datatype like "int23", "string" etc. should be displayed, we work on a fix for this issue. ;-)

**Comment by ReStone** [comment]
I just made a build on the master branch. UaExpert had problems to connect to the server. Connection was permanently lost:
Server:
![master_connection_error](https://cloud.githubusercontent.com/assets/19655759/19122457/d6cbfb14-8b2a-11e6-8eaa-6e017f1e0476.PNG)
UaExpert-Log:
![master_uaexpert_connection_error](https://cloud.githubusercontent.com/assets/19655759/19122475/e6f656b0-8b2a-11e6-91a9-0b41832edd07.PNG)

Still I could verify the ValueRank -3 for the value nodes - during a GOOD impuls of the connction :).

The LabVIEW Client did read 0 as „DataType.Identifier“ for the "Value" nodes and 24 for the other nodes (Name, Type etc.) that still have ValueRank -1:
![masterbranch_nodes_with_rank_minus3](https://cloud.githubusercontent.com/assets/19655759/19122250/e0683148-8b29-11e6-9c4c-c58ab104529e.PNG)

I would conclude LabVIEW does only support ValueRanks 1 and -1 (as mentioned in the support request above).

Do we urgently need ValueRank -3? I could write this to NI and see if they are willing to fix it.

Is it possible to to produce a server with "ValueRanks" 1 and/or -1 and correct „DataType.Identifier“ for at least 1 or 2 variables? I want to give NI some feedback on the topic.

**Comment by jmrahm** [comment]
So finally this issue should be fixed. Every Variable get the more correct ValueRank (1,-1), hence LabView should be happy :-). Additionaly the generic Datatype "BaseDataType" (24)  was replaced by the specific Datatypes (int, string etc) .

For disconnection failure I will start a new issue.  Until then, please check the correctness during the connection of the fix. If it fails, feel free to reopen this issue. (GitHub closed this issue automatically by writing the issue number in the commit comment)
