### ISSUE TITLE
unsubscribing crashes server

### ISSUE THREAD

**Issue by ReStone** [ChimeraTK/ControlSystemAdapter-OPC-UA-Adapter#16]
Just tested Subscription with LabVIEW

Very roughly the code, to subscribe to UA server Nodes in LabVIEW looks like this:
![unsubscribing_crashes_server_lvcode](https://cloud.githubusercontent.com/assets/19655759/19556345/00db6e20-96c1-11e6-94c4-e1ded2bd1089.PNG)

It is working until LabVIEW unsubscribes ("Delete Monitored Nodes.vi" and "Delete Subscriptions.vi") from the server. In this case the server crashes (see last lines in picture below).

![unsubscribing_crashes_server](https://cloud.githubusercontent.com/assets/19655759/19556059/b9cb0a1e-96bf-11e6-8371-b4dccdd03538.PNG)

**Comment by ReStone** [comment]
Some additional information: After this crash it is not possible to run the server in a stable manner. Restarting it brings the server into operation and i.e. UaExpert reconnects to the server. But the connection is permanently closed and opened again.

![server_unstable](https://cloud.githubusercontent.com/assets/19655759/19930648/b0246a74-a109-11e6-9945-475972519957.PNG)

Restarting server or client does not help. Only after rebooting Ubuntu the server runs again.

**Comment by jpfr** [comment]
Cannot reproduce.
Was probably fixed during the update to the recent 0.2 release.
