### ISSUE TITLE
problem with build

### ISSUE THREAD

**Issue by ReStone** [ChimeraTK/ControlSystemAdapter-OPC-UA-Adapter#21]
cmake make just failed:
![unbenannt](https://cloud.githubusercontent.com/assets/19655759/22773487/ab42f5b6-eea2-11e6-84e3-44ae05709a6c.PNG)

**Comment by jmrahm** [comment]
Mhh, it look like a error in DeviceAccess. I change the repo to the original DeviceAccess. Please please try again. ;-)

**Comment by ReStone** [comment]
Just tried. Similar error:
![unbenannt](https://cloud.githubusercontent.com/assets/19655759/22774806/11086a7e-eea9-11e6-8992-b38940dbafb8.PNG)

**Comment by jmrahm** [comment]
In the 4th line, the said "Syntax error: "(" unexpected"
In which file and line occurs the error?

**Comment by ReStone** [comment]
Where can I find this information? I don't see more than in the screenshot.

**Comment by mhier** [comment]
This error is not a C++ error but comes from the shell. Strangely it seems to appear in the middle of the build of DeviceAccess (the library was just built but next the tests would follow, thus is says 29% finished only). The build is not done by a shell script but by make, so this error seems a bit strange.

Anyway, I strongly suggest to move away from the internal build of the ChimeraTK dependencies and use the ChimeraTK-installer instead (https://github.com/ChimeraTK/ChimeraTK-Installer). DeviceAccess itself builds fine on Ubuntu16!

**Comment by ReStone** [comment]
Just created a fresh clone and compilation seems to work again.
However I will have a look at the Installer.

Thanks!
