### ISSUE TITLE
Suggestions for Future Enhancements

### ISSUE THREAD

**Issue by ReStone** [ChimeraTK/ControlSystemAdapter-OPC-UA-Adapter#22]
Testing brought up some things that might be changed in a future version of the adapter and should be mentioned here for later reference:

# Variable Mapping 
## **config** section
- "/" in the rootFolder could be used as folder seperator
- not defining rootFolder automatically creates root folder "mtcaModule", in this case no folder should be created

## **additionalNodes** section
- multiple additionalNodes sections are ignored without warning/error
- it is not possible to build a hierarchie (maybe a "folder" element could be introduced)
- it should be possible to insert additional nodes into subfolders alongside with actual process nodes thus adding integration meta data
- it is possible to generate additional nodes with dublicate browse path

## **application** section
- it is possible to generate nodes with same browse path and content
- it is possible to generate nodes with same browse path and different content
- both does not make sense for ChimeraTK

# Node ID
- String-Node-ID generation has to be revised, some clients display String-Node-IDs as variable names in their configuration. Using the original CTK application variable name bypasses mapping in such a case.

**Comment by ReStone** [comment]
## PV-value
The PV-folder itself should be the node that carries the PV-value.
_example:_
- read/subscribe "root.variables.sine" to get/monitor the sine value
- read/subscribe "root.variables.sine.unit" to get/monitor the unit of the sine value

_further example:_ free UaCpp-Demoserver by Unified Automation is doing it like this.

**Reason:**
- this prooved to be most intuitive in tests with different partly commercial OPC UA servers

**Comment by ReStone** [comment]
# Folder Comments
PV-Manager allows to define comments for PV folders on the application side. These should be mapped to the OPC UA adress space.

**Comment by ichrispa** [comment]
@mhier: Can these comments be accessed from the control-system interface of the pv manager?

**Comment by mhier** [comment]
No, not yet. We have to discuss how to provide this information. Currently the ControlSystemAdapter does not know the concept of branch nodes (=folders), so there is no way to add information there.

**Comment by zenker** [comment]
If I understand the mapping correct, it is not possible to rename a folder but only variable names when using unroll path:
`/path/var1` &rarr; `/path/var2 `is possible
`/path/var1` &rarr; `/path1/var1` is not possible
It would be beneficial to allow also renaming of folders, since it just happened, that variables were moved to a different folder on the server. Maybe one could add an option to switch the renaming and unrolling, i.e. rename before unroll instead of unroll the path and rename after.

**Comment by ichrispa** [comment]
Hi zenker,

all variables are in essence a singular instance in the flat variables folder. Folder are always part of aliases to these variables. Hence folders can not be aliased, nor can variables contained in them - only the original name of a variable may serve as a source. The correct representation would be:

`path.var1` &rarr; `/path/varX `is possible
`path.var1` &rarr; `/path1/var1` is not possible (using unrollpath)

UnrollPath is meant as a convenience function to extract/use names that already conform to a naming scheme as hierarchical sorting elements. In your example, the second variable simply does not conform to the naming scheme and the name can't be meaningfully unrolled.

To accomplish what you want, i'd suggest simply declare a new alias for the variable `path.var1` without using unrollpath:

```
<map sourceVariableName="path.var1" rename="var1" engineeringUnit="" description="">
<folder>path1</folder>
</map>
```

**Comment by zenker** [comment]
Most features have been implemented.
