### ISSUE TITLE
single <map> produces two nodes

### ISSUE THREAD

**Issue by ReStone** [ChimeraTK/ControlSystemAdapter-OPC-UA-Adapter#24]
Tests with the current LLRF-Server show a mapping error:
Variables to map:
![variables](https://cloud.githubusercontent.com/assets/19655759/25942350/e9112c64-363c-11e7-885e-9832883bd24b.PNG)

mapping entry:
![mapping](https://cloud.githubusercontent.com/assets/19655759/25942143/48d4a280-363c-11e7-9287-71826edc6e95.PNG)

result:
![double_nodes_edt](https://cloud.githubusercontent.com/assets/19655759/25942395/089426c2-363d-11e7-8245-b365f0997d08.png)

amplitude node occurs in the desired folder and additionally in the <application> folder.

The issue might be associated with the leading "/" in the variable name.

**Comment by jmrahm** [comment]
Hi ReStone,
there was a missing if/else-statement in the xml parsing methode. Now it should work. ;-)
