### ISSUE TITLE
Tests are spuriously failing

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/ControlSystemAdapter-OPC-UA-Adapter#25]
The tests seem to be failing spuriously from time to time, maybe due to a race condition. I noticed this on Jenkins, where the probability of one out of the 6 builds has failed is quite high. I can also reproduce this on my Ubuntu 16.04 desktop machine by running make test in a while loop until it fails. It seems to be always the test_opcua_processvariable which fails. The error message of the failure is the following:

```
[05/16/2017 15:52:15.639] warning/network       Connection to opc.tcp://localhost:16663 failed. Error: 107: Transport endpoint is not connected
Failed to connect to serveropc.tcp://localhost:16663
/home/mhier/ChimeraTK/sources/ControlSystemAdapter-OPC-UA-Adapter/tests/src/test_opcua_processvariable.cpp(389): error in "ProcessVariableTest::testClientSide": check false failed
[05/16/2017 15:52:15.639] info/network  TCP network layer listening on opc.tcp://mskpcx19821:16663
[05/16/2017 15:52:15.639] info/network  Shutting down the TCP network layer with 0 open connection(s)

*** 1 failure detected in test suite "Master Test Suite"
```

Maybe this has something to do with a TCP port collision? On Jenkins, always two builds are running on the same node at the same time, and the probability of failure seems to be much higher. I can add a lock to protect against running two tests simultaneously on the same node. Still this does not explains why it also fails on my desktop machine where I did not run the tests in parallel.

**Comment by mhier** [comment]
Actually, on Jenkins we already have the protection that the tests are not running in parallel, so the problem must be somewhere else.

**Comment by ichrispa** [comment]
Classic race condition... server is not up yet, but client test thread gets executed.

**Comment by mhier** [comment]
Can you fix that?

**Comment by ichrispa** [comment]
We don't have a direct "server is running and initialized" feedback, but we can delay the test a bit to decrease the likehood of the error.

**Comment by mhier** [comment]
Couldn't the test environment periodically check at start up if the server is reachable? When it is reachable it proceeds with the tests. If it doesn't become reachable for a very long timeout (like 10 seconds), the test should fail. This would give us a very low probability of false failure without the need to wait every time for the entire timeout.

**Comment by mhier** [comment]
The tests are still failing with a large probability due to this race condition. On Jenkins with its 6 configurations the probability that at least one of the configurations fails is around 30%, which is quite annoying.

**Comment by jmrahm** [comment]
Hey, I will take a look at the beginning of next week to this issue.
