### ISSUE TITLE
Missing timestamps in Variables

### ISSUE THREAD

**Issue by ichrispa** [ChimeraTK/ControlSystemAdapter-OPC-UA-Adapter#3]
Timestamps are currently missing. We could remodel the type to be a UADateTime, by we would be missing the indices (index0 and index1).

If the indices are required, we need to adjust the model to match the current implementation.

**Comment by killenb** [comment]
The current time stamp with date/time and two indices is conceptually already deprecated. We are looking for a more generic solution and will probably change the concept. Don't spend time on any implementations here at the moment.

**Comment by ichrispa** [comment]
For now, we just added a timestamp to type every variable. We are just reflecting what the PVManager knows, so if this concept is outdated, we would need some feedback in order to revise it.

Best regards, 

Chris
