### ISSUE TITLE
Remove Scalar/Array Differentiation in modules

### ISSUE THREAD

**Issue by ichrispa** [ChimeraTK/ControlSystemAdapter-OPC-UA-Adapter#4]
A variable will be send as an array if it is an array. Is there a specific reason to treat these separately from the standard variable (if we can encode arrays on the fly)?

Maybe we could just add an "isArray" boolean. That would also match the ProcessVariables C++ attributes, as the MTCA_Variable is essentially only a reflection of that class.

**Comment by killenb** [comment]
For your information, I don't know it help: I am about to add base class to all ProcessVariables so they all have the same container under the hood. We want to use NDRegisterAccessor from the DeviceAccess library to unify DeviceAccess and ControlSystem adapter, as discussed in the kick-off meeting. This is using std::vector< std::vector<T> > as container (implementation detail needed in DeviceAccess). The ControlSystemAdapter will only support dimensions [1][n], not real 2D at the moment.

**Comment by ichrispa** [comment]
Hi @killenb ,

making device access available as PV would be really cool. I'll open a new issue on the subject. This one is kind of fixed :)

best regards,

Chris
