### ISSUE TITLE
Configuration of the unsecure Endpoint does not work as expected

### ISSUE THREAD

**Issue by d-rothe** [ChimeraTK/ControlSystemAdapter-OPC-UA-Adapter#77]
Configuration of the unsecure Endpoint is wrongly implemented, or at least misleading.

Following config line does not provide the unsecure endpoint, other than expected:
` <security unsecure="true" certificate="certs/server_cert.der" privatekey="certs/server_key.der" trustlist="certs/trust" blocklist="certs/blocklists" issuerlist="certs/issuer"/>`

However, if you leave out the 'unsecure' attribute, it does provide the unsecure endpoint, which is not necessarily what you intend:
` <security certificate="certs/server_cert.der" privatekey="certs/server_key.der" trustlist="certs/trust" blocklist="certs/blocklists" issuerlist="certs/issuer"/>`

**Comment by zenker** [comment]
I confirm what you describe and I agree that this is not the intended behavior.
