### ISSUE TITLE
Master  a2015cd8bc350df4efe4f97ef86cfa8056c421d4 does not compile

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ControlSystemAdapter-OPC-UA-Adapter#9]
CMake Error at CMakeLists.txt:88 (add_subdirectory):
  The source directory

    /home/msk_jenkins/workspace/ChimeraTK_OPC_UA_Adapter/buildhosts/Ubuntu1404/tests

  does not contain a CMakeLists.txt file.

**Comment by jmrahm** [comment]
Should be fixed, I added the missing CMakeList.txt file in the "test" directory.

**Comment by killenb** [comment]
Confirmed, compiles fine now. Thanks.
